# contracts/dbt_emit.py — parallel dbt schema.yml fragments (course Step 5)
from __future__ import annotations

from pathlib import Path
from typing import Any

import yaml


def field_to_dbt_tests(field_name: str, spec: dict[str, Any]) -> list[dict[str, Any] | str]:
    """Map a Bitol field spec to dbt test entries."""
    tests: list[dict[str, Any] | str] = []
    if spec.get("required") is True:
        tests.append("not_null")
    if spec.get("unique") is True:
        tests.append("unique")
    if "enum" in spec and spec["enum"]:
        tests.append({"accepted_values": {"values": list(spec["enum"])}})
    # Numeric ranges: enforce in ValidationRunner / Soda; dbt optional macro can mirror.
    # relationships: add manually when staging models + refs exist.
    return tests


def emit_dbt_schema_yml(
    *,
    model_name: str,
    schema_fields: dict[str, dict[str, Any]],
    description: str,
    out_path: Path,
) -> None:
    """Write generated_contracts/{name}_dbt.yml compatible with dbt-core schema files."""
    columns: list[dict[str, Any]] = []
    for col_name in sorted(schema_fields.keys()):
        spec = schema_fields[col_name]
        entry: dict[str, Any] = {"name": col_name}
        if spec.get("description"):
            entry["description"] = str(spec["description"])[:1024]
        tests = field_to_dbt_tests(col_name, spec)
        if tests:
            entry["tests"] = tests
        columns.append(entry)

    payload = {
        "version": 2,
        "models": [
            {
                "name": model_name,
                "description": description,
                "columns": columns,
            }
        ],
    }
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write("# AUTO-GENERATED by ContractGenerator — edit contract YAML, re-run generator.\n")
        yaml.dump(payload, f, default_flow_style=False, sort_keys=False, allow_unicode=True)
